### signup user

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Arjun",
    "email": "arjun@acme.org",
    "workspace": "acme",
    "password": "hunter42"
}

### signup user Alice

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Alice",
    "email": "alice@acme.org",
    "workspace": "acme",
    "password": "hunter42"
}

### signup user Bob

POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Bob",
    "email": "bob@acme.org",
    "workspace": "acme",
    "password": "hunter42"
}

### signin user
# @name signin

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "arjun@acme.org",
    "password": "hunter42"
}

@token = {{signin.response.body.token}}

### signin user(wrong password)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "arjun@acme.org",
    "password": "hunter43"
}

### get user list

GET http://localhost:6688/api/users
Authorization: Bearer {{token}}

### create chat public channel

POST http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "general",
    "members": [1, 2, 3],
    "public": true
}

### create chat private channel

POST http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "private",
    "members": [1, 2],
    "public": false
}

### create chat group chat

POST http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json


{
    "name": "group",
    "members": [1, 2, 3],
    "public": false
}

### get chat list

GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}



### update chat name

PATCH  http://localhost:6688/api/chats/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "general1",
    "members": [1, 2, 3]
}

### update chat members

PATCH http://localhost:6688/api/chats/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "general2",
    "members": [1, 2, 3]
}


### delete chat

DELETE http://localhost:6688/api/chats/4
Authorization: Bearer {{token}}

### delete chat(not found)

DELETE http://localhost:6688/api/chats/8
Authorization: Bearer {{token}}


### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="test.png"
Content-Type: application/octet-stream

< /Users/arjun/Desktop/test.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--


### get files

GET http://localhost:6688/api/files/1/d69/9f0/7150c00330707f524a8b290f5361a44ed0
Authorization: Bearer {{token}}

### get files

GET http://localhost:6688/api/files/1/0a0/a9f/2a6772942557ab5355d76af442f8f65e01
Authorization: Bearer {{token}}


### send message

POST http://localhost:6688/api/chats/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "Hello, world! js",
    "files": []
}

### get messages

GET http://localhost:6688/api/chats/1/messages?last_id=5&limit=6
Authorization: Bearer {{token}}
